Revert `s3gw` to `0.14.0`
epinio/helm-charts pull request #467
Opened 2023-07-18 12:43 UTC by enrichman

Since we are close to the release and we have faced some problems during the upgrade of the `s3gw` we would like to have more time to investigate those issues, and provide a clean upgrade release note.

This revert the `s3gw` to the version `0.14.0` (https://github.com/epinio/helm-charts/pull/459/files) and remove the fix introduced in https://github.com/epinio/helm-charts/pull/463.

For the update we also need to add this: https://github.com/epinio/helm-charts/pull/466

/cc @thehejik @giubacc

2023-07-18 13:14 UTC, giubacc requested changes

2023-07-18 13:14 UTC, giubacc commented on chart/epinio/values.yaml
> -  defaultUserCredentialsSecret: s3gw-creds
I would leave this, no need to remove, when we will retry a bump we will already have this.

2023-07-18 13:36 UTC, thehejik approved these changes
Tested incl. sample app deployment using s3gw store, all good.

2023-07-18 13:57 UTC, giubacc approved these changes

2023-07-19 14:00 UTC, merged

2023-07-20 10:39 UTC, thehejik commented
Verified fixed in epinio v1.9.0-rc5